- name: Dan Kaplun
  email: dbkaplun@gmail.com
  num_commits: 2
  first_commit: 2015-09-19 22:21:48
  github: dbkaplun
- name: Alex Taber
  email: aft.pokemon@gmail.com
  num_commits: 11
  first_commit: 2015-12-14 15:34:03
  github: astronautlevel2
- name: Dan Pasanen
  email: invisiblek@cyanogenmod.org
  num_commits: 1
  first_commit: 2016-10-11 19:08:59
  github: invisiblek
- name: Birger Jarl
  email: codefuhrer@gmail.com
  num_commits: 3
  first_commit: 2018-11-03 17:42:42
  github: ingria
- name: Marcus Willock
  email: crazcalm@gmail.com
  aliases:
  - Crazcalm
  num_commits: 1
  first_commit: 2019-10-07 14:36:31
  github: crazcalm
- name: Dario Ostuni
  email: another.code.996@gmail.com
  num_commits: 1
  first_commit: 2016-03-23 19:17:58
  github: dariost
- name: Tim Austin
  email: tim@neenjaw.com
  num_commits: 1
  first_commit: 2019-07-22 00:40:02
  github: neenjaw
- name: Barbz
  email: BarbzYHOOL@users.noreply.github.com
  num_commits: 1
  first_commit: 2018-07-03 15:32:35
  github: BarbzYHOOL
- name: Daniel Harbor
  email: dharbor@paypal.com
  num_commits: 1
  first_commit: 2019-06-29 00:43:05
  github: danielharbor
- name: Kyle Stiemann
  email: stiemannkj1@gmail.com
  num_commits: 1
  first_commit: 2014-09-30 17:40:22
  github: stiemannkj1
- name: Simon Volpert
  email: simon@simonvolpert.com
  num_commits: 20
  first_commit: 2015-06-17 12:33:00
- name: Víctor Pont
  email: victor@pont.cat
  num_commits: 1
  first_commit: 2019-10-02 05:08:36
  github: vpont
- name: Alexey Melezhik
  email: melezhik@gmail.com
  num_commits: 1
  first_commit: 2019-03-07 12:44:55
  github: melezhik
- name: Martin Wimpress
  email: martin.wimpress@flightdataservices.com
  num_commits: 1
  first_commit: 2012-11-26 06:17:20
  github: flexiondotorg
- name: Mariusz Smykuła
  email: mariuszs@gmail.com
  num_commits: 8
  first_commit: 2013-05-31 16:32:45
  github: mariuszs
- name: Xavier Gouchet
  email: xavier.gouchet@gmail.com
  num_commits: 1
  first_commit: 2016-12-10 04:50:00
  github: xgouchet
- name: Marin Marusic
  email: mormy@wanderer.local
  alternate_emails:
  - marin@netpunk.net
  num_commits: 1
  first_commit: 2016-02-08 18:52:38
  github: mormy
- name: divinity76
  email: divinity76@gmail.com
  num_commits: 3
  first_commit: 2016-10-13 18:23:41
  github: divinity76
- name: Elliot Saba
  email: staticfloat@gmail.com
  num_commits: 1
  first_commit: 2013-07-23 00:24:55
  github: staticfloat
- name: Jason Ormand
  email: jason.ormand1@gmail.com
  num_commits: 1
  first_commit: 2012-09-26 10:56:21
  github: okor
- name: Ian Mustafa
  email: cuplizian@yahoo.com
  num_commits: 1
  first_commit: 2014-10-04 20:42:44
  github: cuplizian
- name: Aryan Ebrahimpour
  email: aryanebrahimpour@gmail.com
  num_commits: 2
  first_commit: 2019-06-21 05:26:09
  github: 0xaryan
- name: Michał Kiełbowicz
  email: jupblb@users.noreply.github.com
  num_commits: 1
  first_commit: 2019-04-15 11:50:31
  github: jupblb
- name: Paduct
  email: paduct@list.ru
  aliases:
  - Bro
  num_commits: 2
  first_commit: 2017-01-12 04:25:39
  github: Paduct
- name: Steven Honeyman
  email: stevenhoneyman@users.noreply.github.com
  num_commits: 1
  first_commit: 2014-06-21 19:02:33
  github: stevenhoneyman
- name: Filip Szymański
  email: fszymanski@users.noreply.github.com
  num_commits: 1
  first_commit: 2018-09-10 08:25:37
  github: fszymanski
- name: kaernyk
  email: kaernyk@users.noreply.github.com
  num_commits: 1
  first_commit: 2014-06-20 14:23:58
  github: kaernyk
- name: Michael Lopez
  email: michael@weahead.se
  num_commits: 1
  first_commit: 2015-04-21 03:00:55
  github: michaellopez
- name: nl6720
  email: nl6720@gmail.com
  num_commits: 4
  first_commit: 2016-02-05 11:34:08
  github: nl6720
- name: amateursuperuser
  email: shadekophi@outlook.com
  num_commits: 1
  first_commit: 2015-07-23 13:39:17
  github: amateursuperuser
- name: Ville Pulkkinen
  email: ville.p.pulkkinen@gmail.com
  num_commits: 1
  first_commit: 2014-07-31 06:57:13
  github: vvillee
- name: Brandon LeBlanc
  email: brandon@leblanc.codes
  num_commits: 1
  first_commit: 2018-08-27 10:57:14
  github: demosdemon
- name: Jody Leonard
  email: me@jodyleonard.com
  num_commits: 2
  first_commit: 2015-10-24 05:52:47
  github: jodizzle
- name: matnovak
  email: matnovak@foi.hr
  num_commits: 1
  first_commit: 2019-09-25 04:54:00
- name: Mani Tadayon
  email: bowsersenior@gmail.com
  num_commits: 1
  first_commit: 2012-09-12 23:44:09
  github: bowsersenior
- name: TSUYUSATO Kitsune
  email: make.just.on@gmail.com
  num_commits: 1
  first_commit: 2017-06-30 03:30:16
  github: MakeNowJust
- name: Navid Alipour
  email: navid9675@gmail.com
  num_commits: 1
  first_commit: 2019-05-10 18:40:23
  github: navid9675
- name: Austin
  email: gtbjj@users.noreply.github.com
  num_commits: 1
  first_commit: 2016-02-15 23:30:25
  github: gtbjj
- name: CirKu17
  email: cirku17@gmail.com
  alternate_emails:
  - CirKu17@gmail.com
  num_commits: 3
  first_commit: 2011-06-15 06:35:47
  github: CirKu17
- name: Geoffrey McClinsey
  email: gmcclins@hashbang.sh
  num_commits: 3
  first_commit: 2017-12-28 00:24:09
  github: gmcclins
- name: Daniel Jones
  email: tortxof@gmail.com
  num_commits: 2
  first_commit: 2014-05-11 18:41:00
  github: tortxof
- name: Luis Lobo Borobia
  email: luislobo@gmail.com
  num_commits: 1
  first_commit: 2017-01-23 12:00:40
  github: luislobo
- name: Lephend
  email: MLephend@sms1.local
  num_commits: 1
  first_commit: 2016-01-05 10:39:28
  github: idpwf
- name: Brandon Gulla
  email: blgulla@rd6um-34106l.infosec.tycho.ncsc.mil
  alternate_emails:
  - brandon@brandongulla.com
  num_commits: 2
  first_commit: 2015-09-18 14:28:59
  github: bgulla
- name: Thomas Rosenau
  email: thomasr@fantasymail.de
  aliases:
  - ThomasR
  num_commits: 4
  first_commit: 2016-02-28 08:15:46
  github: ThomasR
- name: Sandro Jäckel
  email: sandro.jaeckel@gmail.com
  github: SuperSandro2000
  aliases:
  - Sandro
  num_commits: 3
  first_commit: 2019-03-15 03:31:46
- name: maritaria
  email: bramkamies@gmail.com
  num_commits: 1
  first_commit: 2016-04-30 13:44:51
  github: maritaria
- name: Alessandro Luppi
  email: luppi.alle@gmail.com
  num_commits: 1
  first_commit: 2016-09-27 13:21:15
  github: hawk93
- name: Harsh Shandilya
  email: msfjarvis@gmail.com
  num_commits: 13
  first_commit: 2019-09-19 15:52:44
  github: msfjarvis
  alternate_emails:
  - me@msfjarvis.dev
- name: DesertPunk
  email: 38014530+DesertPunk@users.noreply.github.com
  num_commits: 2
  first_commit: 2019-04-07 11:05:34
  github: DesertPunk
- name: floomby
  email: caboodlennm@gmail.com
  num_commits: 1
  first_commit: 2014-03-06 18:41:01
  github: floomby
- name: esler
  email: esler@users.noreply.github.com
  num_commits: 1
  first_commit: 2017-05-25 07:35:02
  github: esler
- name: Karl
  email: karlding@users.noreply.github.com
  num_commits: 1
  first_commit: 2017-02-04 05:22:03
  github: karlding
- name: Eric Wieser
  email: wieser.eric@gmail.com
  num_commits: 1
  first_commit: 2015-04-14 05:14:31
- name: Evan Troy Owen
  email: 2evanowen@gmail.com
  num_commits: 1
  first_commit: 2016-03-02 19:46:31
  github: evanowen
- name: Mickaël Bernardini
  email: contact@mickael-bernardini.fr
  num_commits: 1
  first_commit: 2015-11-14 04:22:22
  github: mikafouenski
- name: sledgeh
  email: sledgeh@users.noreply.github.com
  num_commits: 1
  first_commit: 2017-04-23 16:16:19
  github: sledgeh
- name: Matthew Cox
  email: matthewcpcox@gmail.com
  num_commits: 4
  first_commit: 2014-08-02 18:12:13
  github: MatthewCox
- name: Shmueli Englard
  email: shmueli.yosef@englard.net
  num_commits: 2
  first_commit: 2017-03-29 12:52:08
  github: SamuelEnglard
- name: Ondrej Esler
  email: esler.ondrej@gmail.com
  num_commits: 2
  first_commit: 2018-04-03 16:49:51
  github: esler
- name: Per Lundberg
  email: per.lundberg@ecraft.com
  num_commits: 1
  first_commit: 2018-04-23 08:28:19
  github: perlun
- name: Brian Recchia
  email: brian@recchia.name
  num_commits: 1
  first_commit: 2017-01-03 17:07:03
- name: Daniel Kaplun
  email: dan@beardtree.com
  num_commits: 5
  first_commit: 2013-12-20 00:48:22
  github: beardtree
- name: Ralf Brandenstein
  email: nooitaf@users.noreply.github.com
  num_commits: 1
  first_commit: 2019-03-17 02:55:13
  github: nooitaf
- name: Tiago Programmer
  email: TJProgrammer@users.noreply.github.com
  num_commits: 1
  first_commit: 2019-09-12 19:35:14
  github: TJProgrammer
- name: Anthony Scopatz
  email: scopatz@gmail.com
  num_commits: 52
  first_commit: 2010-07-28 18:15:43
  github: astronautlevel
- name: PhilipRoman
  email: dev.philipjohn@gmail.com
  num_commits: 1
  first_commit: 2019-06-26 16:03:20
  github: PhilipRoman
- name: pik
  email: alexander.maznev@gmail.com
  num_commits: 1
  first_commit: 2017-02-21 07:25:43
  github: pik
- name: Michael Straube
  email: m.s.online@gmx.de
  alternate_emails:
  - straubem@gmx.de
  num_commits: 7
  first_commit: 2016-06-10 15:24:25
  github: arisinfenix
- name: Sander M
  email: S.N.Maijers@gmail.com
  num_commits: 1
  first_commit: 2015-09-26 15:13:07
- name: jboero
  email: boeroboy@gmail.com
  num_commits: 2
  first_commit: 2018-10-23 04:49:30
  github: jboero
- name: mcnesium
  email: mcnesium@users.noreply.github.com
  num_commits: 1
  first_commit: 2018-06-18 07:40:34
  github: mcnesium
- name: Philipp Leo Dylong
  email: creekpld@gmail.com
  num_commits: 3
  first_commit: 2016-04-29 15:21:21
  github: creekpld
- name: EarthCitizen
  email: EarthCitizen@users.noreply.github.com
  num_commits: 1
  first_commit: 2016-03-03 12:39:44
  github: EarthCitizen
- name: CoffeeTableEnnui
  email: thiabaud.engelbrecht@gmail.com
  num_commits: 7
  first_commit: 2016-08-29 00:02:37
  github: CoffeeTableEnnui
- name: lopho
  email: lopho@users.noreply.github.com
  num_commits: 2
  first_commit: 2019-02-27 10:08:50
  github: lopho
- name: Elof
  email: elofu17@users.noreply.github.com
  num_commits: 23
  first_commit: 2016-12-06 13:11:24
  github: elofu17
- name: Jon Langevin
  email: intel352@gmail.com
  num_commits: 1
  first_commit: 2012-10-12 11:26:13
  github: intel352
- name: Eric Ma
  email: ericmajinglong@gmail.com
  github: ericmjl
  num_commits: 1
  first_commit: 2018-05-27 13:29:36
- name: tomcharter365
  email: 31257796+tomcharter365@users.noreply.github.com
  num_commits: 1
  first_commit: 2018-10-11 17:20:56
  github: tomcharter365
- name: Skruppy
  email: skruppy@onmars.eu
  num_commits: 1
  first_commit: 2019-07-09 13:16:52
  github: Skrupellos
- name: Austin Jackson
  email: themacphage@gmail.com
  num_commits: 1
  first_commit: 2019-04-24 21:07:13
  github: au5ton
- name: Paul Inder
  email: paulinder@gmail.com
  num_commits: 2
  first_commit: 2014-08-01 19:29:24
  github: paulinder
- name: Coşku Baş
  email: cosku.bas@gmail.com
  num_commits: 2
  first_commit: 2016-02-16 14:41:14
  github: tapir
- name: Markus Hoffmann
  email: kollo@users.sourceforge.net
  num_commits: 1
  first_commit: 2019-06-05 06:45:35
  github: kollokollo
- name: Anomitee
  email: Anomitee@gmail.com
  num_commits: 2
  first_commit: 2014-01-04 01:32:57
  github: Anomitee
- name: Philipp
  email: creekpld@users.noreply.github.com
  num_commits: 5
  first_commit: 2016-03-07 16:32:57
  github: creekpld
- name: Natalie Somersall
  email: natalie.somersall@gmail.com
  num_commits: 1
  first_commit: 2015-08-20 09:14:32
- name: Damian Mee
  email: mee.damian@gmail.com
  num_commits: 1
  first_commit: 2016-07-17 06:49:28
  github: meeDamian
- name: Aaron Bishop
  email: erroneous@gmail.com
  num_commits: 1
  first_commit: 2016-06-03 10:46:57
  github: Erroneous1
- name: Adrien Pyke
  email: adpyke@gmail.com
  num_commits: 1
  first_commit: 2018-06-22 14:10:04
  github: kufii
- name: Cody
  email: ChaosZero112@users.noreply.github.com
  num_commits: 1
  first_commit: 2018-07-14 19:16:55
  github: ChaosZero112
- name: Jan Trejbal
  email: jan.trejbal@gmail.com
  num_commits: 1
  first_commit: 2016-07-07 07:27:40
  github: Trejjam
- name: Tiago Almeida
  email: tjamadeira@gmail.com
  num_commits: 5
  first_commit: 2019-09-12 19:16:01
  github: TJProgrammer
- name: Bryan Ross
  email: bryan@liquidstate.net
  num_commits: 2
  first_commit: 2014-08-02 04:05:51
  github: liquidstate
- name: Huub de Beer
  email: Huub@heerdebeer.org
  num_commits: 3
  first_commit: 2017-07-16 07:46:55
  github: htdebeer
- name: Mikael O. Bonnier
  email: mikael.bonnier@gmail.com
  github: mobluse
  num_commits: 3
  first_commit: 2018-05-12 06:55:08
- name: TUSF
  email: ragef33@gmail.com
  num_commits: 1
  first_commit: 2017-12-21 00:49:51
  github: TUSF
- name: Jeppe Fihl-Pearson
  email: jeppe@tenzer.dk
  num_commits: 3
  first_commit: 2019-07-27 03:53:05
  github: Tenzer
- name: Nicholas Christopoulos
  email: nereusx@users.noreply.github.com
  num_commits: 2
  first_commit: 2017-07-15 22:26:56
  github: nereusx
- name: grandtheftjiujitsu
  email: austin.haedicke@gmail.com
  num_commits: 1
  first_commit: 2015-06-21 15:09:30
  github: grandtheftjiujitsu
- name: John S Long
  email: john@128.io
  github: adduc
  num_commits: 1
  first_commit: 2015-12-15 02:44:09
- name: Ondřej Ešler
  email: ondrej.esler@intraworlds.com
  num_commits: 3
  first_commit: 2018-12-13 04:48:50
  github: esler
- name: Ghost-NULL
  email: maatpeter@hotmail.com
  num_commits: 1
  first_commit: 2013-10-20 18:03:28
- name: PN Wu (小平)
  email: PingNote@users.noreply.github.com
  num_commits: 1
  first_commit: 2018-08-15 03:22:08
  github: PingNote
- name: yochem
  email: yochem@users.noreply.github.com
  num_commits: 5
  first_commit: 2018-05-03 07:37:35
  github: yochem
- name: Andrea Dejan Grande
  email: dejan-grande@mail.com
  num_commits: 12
  first_commit: 2019-04-27 17:19:34
  github: AndreaDejanGrande
- name: Sina
  email: sina6002@gmail.com
  num_commits: 2
  first_commit: 2014-08-02 00:24:56
  github: sinaa
- name: Ross Smith II
  email: ross@smithii.com
  num_commits: 2
  first_commit: 2019-06-06 02:27:13
  github: rasa
- name: Zach DeCook
  email: zdecook@ccel.org
  alternate_emails:
  - zachdecook@librem.one
  num_commits: 10
  first_commit: 2019-12-18 09:34:49
  github: earboxer
- name: Gareth Jones
  email: Jones258@Gmail.com
  num_commits: 11
  first_commit: 2019-11-01 23:57:35
- name: Dante Falzone
  email: 48266179+DanteFalzone0@users.noreply.github.com
  num_commits: 8
  first_commit: 2019-12-25 22:55:19
  github: DanteFalzone0
- name: CryptoDragonLady
  email: celeste.weingartner@gmail.com
  num_commits: 1
  first_commit: 2019-12-30 04:00:29
  github: CryptoDragonLady
- name: Hunter Peavey
  email: vrywjvgviuotxeioqipx@disroot.org
  num_commits: 2
  first_commit: 2019-10-18 19:38:17
  github: krathalan
- name: Ritiek Malhotra
  email: Ritiek@users.noreply.github.com
  num_commits: 4
  first_commit: 2017-05-23 11:12:47
  github: ritiek
- name: hdquemada
  email: 44162051+hdquemada@users.noreply.github.com
  num_commits: 4
  first_commit: 2020-04-26 23:09:25
  github: hdquemada
- name: Oïleurre
  email: 66210874+oileurre@users.noreply.github.com
  num_commits: 2
  first_commit: 2020-06-07 07:20:21
  github: oileurre
- name: Joerg Stoever
  email: stoever@dtv-verkehrsconsult.de
  num_commits: 1
  first_commit: 2020-08-14 06:04:10
  github: Gaibhne
- name: emidiostani
  email: emidiostani@gmail.com
  num_commits: 1
  first_commit: 2020-02-05 05:48:21
  github: EmidioStani
- name: Justin P
  email: Jpartain89@gmail.com
  num_commits: 1
  first_commit: 2020-01-30 23:28:08
  github: jpartain89
- name: Yvan Satyawan
  email: y_satyawan@hotmail.com
  num_commits: 2
  first_commit: 2020-03-16 08:40:58
  github: yvan674
- name: Paulo S. Costa
  email: pauloscosta5@gmail.com
  num_commits: 2
  first_commit: 2020-01-27 17:18:02
  github: pscosta5
- name: czechuuu
  email: czechuuu@users.noreply.github.com
  num_commits: 1
  first_commit: 2020-08-26 12:13:33
  github: czechuuu
- name: msuska
  email: Martin.Suska@dhl.com
  num_commits: 1
  first_commit: 2020-03-21 10:18:26
  github: Betlista
- name: davidhcefx
  email: davidhu0903ex3@gmail.com
  num_commits: 3
  first_commit: 2020-08-30 21:21:54
  github: davidhcefx
- name: Mlendea, Horațiu
  email: Mlendea.Horatiu@GMail.com
  num_commits: 2
  first_commit: 2020-02-09 03:50:20
  github: hmlendea
- name: Exonorid
  email: exonorid@gmail.com
  num_commits: 1
  first_commit: 2020-10-02 02:46:00
  github: Exonorid
- name: yzzyx
  email: yzzyx@yzzyx.network
  alternate_emails:
  - yzzyx@cock.li
  num_commits: 3
  first_commit: 2020-04-24 09:22:09
- name: Aiden Gall
  email: aidentvgall@gmail.com
  num_commits: 1
  first_commit: 2020-03-14 18:09:11
  github: Wasby
- name: Rashil Gandhi
  email: rashil2000@gmail.com
  num_commits: 1
  first_commit: 2020-08-10 08:12:56
  github: rashil2000
- name: Ryan Westlund
  email: rlwestlund@gmail.com
  num_commits: 2
  first_commit: 2020-04-08 08:16:57
  github: yujiri8
- name: Serhiy Zahoriya
  email: serhiy.int@gmail.com
  num_commits: 1
  first_commit: 2020-10-08 10:43:13
- name: Bart Hanssens
  email: bart.hanssens@bosa.fgov.be
  num_commits: 1
  first_commit: 2020-10-07 11:30:35
  github: Fedict
