---
services:
  logzio-shipper:
    image: logzio/fluentd-docker-logs:latest
    container_name: logzio-shipper
    ports:
      - 127.0.0.1:6002:5001
    environment:
      - LOGZIO_LOG_SHIPPING_TOKEN=__MYLOGZIOTOKEN__
      - LOGZIO_LOG_LISTENER=https://listener.logz.io:8071
      - LOGZIO_TYPE=docker-fluentd
      - ADDITIONAL_FIELDS=docker.host=__MYHOSTNAME__
    volumes:
      - /opt/docker/data/logzio/fluentd-log:/fluentd/log
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers
    restart: always
