#!/usr/bin/env bash

# use in a script with cecho available...
# source ./cecho

function setupnote() {
  if [  $# -ne 2 ]; then
    echo "setupnote checks whether the given artifact already appears in ~/SystemSetup.md, and if not it adds the given Markdown string to the checklist."
    echo ""
    echo "Usage: setupnote \"Artifact Name\"  \\"
    # shellcheck disable=SC2028
    echo "                 \"- [ ] configure it\\n- [ ] test it\""
    return 1
  fi

  ARTIFACT_NAME="$1"
  ARTIFACT_NAME=$(echo "$ARTIFACT_NAME" | sed 's/\.app$//' | sed 's/^\/Applications\///' | sed 's/^\/opt\/homebrew\/bin\///' | sed 's/^\/usr\/local\/bin\///')
  TODOS="$2"

  if ! grep -c "## $ARTIFACT_NAME" "$HOME/SystemSetup.md" >/dev/null; then
    # shellcheck disable=SC2129
    echo "## $ARTIFACT_NAME" >> "$HOME/SystemSetup.md"
    echo "" >> "$HOME/SystemSetup.md"
    echo -e "$TODOS" >> "$HOME/SystemSetup.md"
    echo "" >> "$HOME/SystemSetup.md"
  fi
}

function sw_install() {
  if [  $# -lt 2 ]; then
    echo "sw_install checks whether an artifact is present, and if not it runs the given command."
    echo "If given a third argument, that string will be appended to ~/SystemSetup.md after installation."
    echo ""
    echo "Usage: sw_install /path/to/artifact  \\"
    echo "                 \"brew install packagename\"  \\"
    # shellcheck disable=SC2028
    echo "                 \"- [ ] configure it\\n- [ ] test it\""
    return 1
  fi

  ARTIFACT="$1"
  INSTALL_CMD="$2"
  TODOS="$3"

  if [ -e "$ARTIFACT" ]; then
    cecho "✔ $ARTIFACT already exists." $green
    return 0
  fi

  function brew_install() {
    brew install "$1"
    CAVEATS="$(brew caveats "$1" | tail -n +2)"
    if [[ -n "$CAVEATS" ]]; then
      if [[ -n "$TODOS" ]]; then
        TODOS="$TODOS\n\n"
      fi
      TODOS="$TODOS### Homebrew Caveats\n\`\`\`\n$CAVEATS\n\`\`\`"
    fi
  }

  function brew_cask_install() {
    brew install --cask "$1"
    CAVEATS="$(brew caveats "$1" | tail -n +2)"
    if [[ -n "$CAVEATS" ]]; then
      if [[ -n "$TODOS" ]]; then
        TODOS="$TODOS\n\n"
      fi
      TODOS="$TODOS### Homebrew Caveats\n\`\`\`\n$CAVEATS\n\`\`\`"
    fi
  }

  ASK=${CDZ_EVERYTHING_OPTIONAL:-false}
  if [ "$ASK" = true ]; then
    cecho "Install $ARTIFACT? (y/N)   (mode: everything is optional)" $magenta
    read -r response
    if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
      echo ""
      cecho "Installing $ARTIFACT..." $cyan
      eval "$INSTALL_CMD"
      if [[ -n "$TODOS" ]]; then
        setupnote "$ARTIFACT" "$TODOS"
      fi
    fi
  else
    echo ""
    cecho "Installing $ARTIFACT..." $cyan
    eval "$INSTALL_CMD"
    if [[ -n "$TODOS" ]]; then
      setupnote "$ARTIFACT" "$TODOS"
    fi
  fi
}
